@TaskManagerAPI_HostAddress = https://localhost:7263

POST {{TaskManagerAPI_HostAddress}}/api/tasks
Content-Type: application/json

{
  "name": "—ходить в уник",
  "description": "завтра"
}

###

GET {{TaskManagerAPI_HostAddress}}/api/tasks

###
